sudo: required
dist: trusty
language: node_js

branches:
  only:
  - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  sonarcloud:
    organization: "marissa-hagglund-github" # the key of the org

capabilities:
  browserName:
      - chrome

node_js:
  - "8.9.0"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

after_install:
  - npm rebuild node-sass

before_script:
  - node ./node_modules/protractor/bin/webdriver-manager update
  - npm rebuild node-sass
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - sonar-scanner
  - npm run rimraf -- compiled
  - npm run ci:travis
